<?php
/** @var Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
$errors = $viewModel->getVariable('changesErrors', []);
$changes = $viewModel->getVariable('changes', []);

$name = isset($changes['name']) ? $changes['name'] : null;
$age = isset($changes['age']) ? $changes['age'] : null;
?>
<h1>Create user</h1>
<form action="/users/user/create" method="post">
    <div class="form-group<?= (isset($errors['name'])) ? ' has-error' : '' ?>">
        <label class="control-label" for="name">Name:</label>
        <input class="form-control" id="name" type="text" name="name" value="<?= $name ?>" />
        <?php if (!empty($errors['name'])): ?>
            <?php foreach ($errors['name'] as $error): ?>
                <span class="help-block"><?= $error ?></span>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <button type="submit" class="btn btn-default">Create</button>
</form>
