<?php
/** @var Zend\View\Model\ViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();
/** @var  $result */
$result = $viewModel->getVariable('result');

$id = isset($result['id']) ? $result['id'] : null;
$name = isset($result['name']) ? $result['name'] : null;
?>
<h1>Read user</h1>
<form action="/users/user/update/<?= $id ?>" method="post">
    <div class="form-group">
        <label class="control-label" for="name">Name:</label>
        <input class="form-control" id="name" type="text" name="name" value="<?= $name ?>" />
    </div>
    <button type="submit" class="btn btn-default">Update</button>
</form>
